### ISSUE TITLE
Create UI Layouts 

### ISSUE THREAD

**Issue by kchin28** [CMPUT301F16T09/Unter#1]
Use agreed colour scheme 
Keep "hamburger" toolbar

**Comment by kwong4** [comment]
Create the java classes w/ each activity you make.

Aka do New-> Activity so each class is created with each activity.

![screenshot](https://cloud.githubusercontent.com/assets/22039913/19622513/cd4d0574-9868-11e6-9453-7b61943316ce.png)

**Comment by DanielTran3** [comment]
Make sure you select "Basic Activity" and not "Empty Activity"
